- generic [active] [ref=e1]:
  - generic [ref=e2]:
    - generic [ref=e4713]:
      - complementary [ref=e4714]:
        - generic [ref=e4715]:
          - img [ref=e4717]
          - generic [ref=e4718]: MediZen
        - generic [ref=e4719]:
          - heading [level=2] [ref=e4720]: Đăng nhập hệ thống
          - paragraph [ref=e4721]: Quản lý phòng khám
        - generic [ref=e4722]:
          - generic [ref=e4723]:
            - img [ref=e4724]
            - generic [ref=e4727]: Patient-first
          - generic [ref=e4728]:
            - img [ref=e4729]
            - generic [ref=e4731]: Real-time queue
          - generic [ref=e4732]:
            - img [ref=e4733]
            - generic [ref=e4735]: RBAC + audit
      - main [ref=e4736]:
        - generic [ref=e4737]:
          - generic [ref=e4738]:
            - heading "Đăng nhập hệ thống" [level=1] [ref=e4739]
            - paragraph [ref=e4740]: Quản lý phòng khám
          - generic [ref=e4741]:
            - generic [ref=e4742]:
              - text: Tên đăng nhập
              - generic [ref=e4743]:
                - img
                - textbox "Tên đăng nhập" [ref=e4744]:
                  - /placeholder: Nhập tên đăng nhập
            - generic [ref=e4745]:
              - generic [ref=e4746]:
                - generic [ref=e4747]: Mật khẩu
                - button "Quên mật khẩu?" [ref=e4748] [cursor=pointer]
              - generic [ref=e4749]:
                - img
                - textbox "Mật khẩu" [ref=e4750]:
                  - /placeholder: Nhập mật khẩu
                - button "Show password" [ref=e4751] [cursor=pointer]:
                  - img [ref=e4752]
            - generic [ref=e4755]:
              - checkbox "Ghi nhớ đăng nhập" [ref=e4756] [cursor=pointer]
              - checkbox
              - generic [ref=e4757] [cursor=pointer]: Ghi nhớ đăng nhập
            - button "Đăng nhập" [ref=e4758] [cursor=pointer]
          - paragraph [ref=e4759]: © 2026 MediZen · v0.1.0
    - region "Notifications alt+T"
  - generic [ref=e392]: "0"