- generic [ref=e2]:
  - generic [ref=e3]:
    - complementary [ref=e4]:
      - generic [ref=e5]:
        - img [ref=e7]
        - generic [ref=e8]: MediZen
      - generic [ref=e9]:
        - heading [level=2] [ref=e10]: Đăng nhập hệ thống
        - paragraph [ref=e11]: Quản lý phòng khám
      - generic [ref=e12]:
        - generic [ref=e13]:
          - img [ref=e14]
          - generic [ref=e17]: Patient-first
        - generic [ref=e18]:
          - img [ref=e19]
          - generic [ref=e21]: Real-time queue
        - generic [ref=e22]:
          - img [ref=e23]
          - generic [ref=e25]: RBAC + audit
    - main [ref=e26]:
      - generic [ref=e27]:
        - generic [ref=e28]:
          - heading "Đăng nhập hệ thống" [level=1] [ref=e29]
          - paragraph [ref=e30]: Quản lý phòng khám
        - generic [ref=e31]:
          - alert [ref=e50]:
            - img [ref=e51]
            - paragraph [ref=e54]: Đã xảy ra lỗi. Vui lòng thử lại.
          - generic [ref=e32]:
            - text: Tên đăng nhập
            - generic [ref=e33]:
              - img
              - textbox "Tên đăng nhập" [ref=e34]:
                - /placeholder: Nhập tên đăng nhập
                - text: admin
          - generic [ref=e35]:
            - generic [ref=e36]:
              - generic [ref=e37]: Mật khẩu
              - button "Quên mật khẩu?" [ref=e38] [cursor=pointer]
            - generic [ref=e39]:
              - img
              - textbox "Mật khẩu" [ref=e40]:
                - /placeholder: Nhập mật khẩu
                - text: Demo@1234
              - button "Show password" [ref=e41] [cursor=pointer]:
                - img [ref=e42]
          - generic [ref=e45]:
            - checkbox "Ghi nhớ đăng nhập" [ref=e46] [cursor=pointer]
            - checkbox
            - generic [ref=e47] [cursor=pointer]: Ghi nhớ đăng nhập
          - button "Đăng nhập" [ref=e48] [cursor=pointer]
        - paragraph [ref=e49]: © 2026 MediZen · v0.1.0
  - region "Notifications alt+T"