- generic [active] [ref=e1]:
  - generic [ref=e2]:
    - generic [ref=e3]:
      - complementary [ref=e4]:
        - generic [ref=e5]:
          - img "MediZen" [ref=e6]
          - generic [ref=e7]: MediZen
        - navigation [ref=e8]:
          - link "Tổng quan" [ref=e9] [cursor=pointer]:
            - /url: "#/dashboard"
            - img [ref=e10]
            - generic [ref=e15]: Tổng quan
          - generic [ref=e16]:
            - button "Tiếp tân" [ref=e17] [cursor=pointer]:
              - img [ref=e18]
              - generic [ref=e20]: Tiếp tân
              - img [ref=e21]
            - generic [ref=e23]:
              - link "Bệnh nhân" [ref=e24] [cursor=pointer]:
                - /url: "#/patients"
                - img [ref=e25]
                - generic [ref=e30]: Bệnh nhân
              - link "Lịch hẹn" [ref=e31] [cursor=pointer]:
                - /url: "#/appointments"
                - img [ref=e32]
                - generic [ref=e36]: Lịch hẹn
              - link "Hàng chờ" [ref=e37] [cursor=pointer]:
                - /url: "#/queue"
                - img [ref=e38]
                - generic [ref=e42]: Hàng chờ
          - generic [ref=e43]:
            - button "Nhà thuốc active role" [ref=e44] [cursor=pointer]:
              - img [ref=e45]
              - generic [ref=e48]: Nhà thuốc
              - generic "active role" [ref=e49]
              - img [ref=e50]
            - generic [ref=e52]:
              - link "Cấp phát chờ" [ref=e53] [cursor=pointer]:
                - /url: "#/pharmacy/pending"
                - img [ref=e54]
                - generic [ref=e56]: Cấp phát chờ
              - link "Đổi lô thuốc" [ref=e57] [cursor=pointer]:
                - /url: "#/pharmacy/substitute"
                - img [ref=e58]
                - generic [ref=e61]: Đổi lô thuốc
              - link "Tồn kho" [ref=e62] [cursor=pointer]:
                - /url: "#/pharmacy/inventory"
                - img [ref=e63]
                - generic [ref=e73]: Tồn kho
              - link "Kiểm kê điều chỉnh" [ref=e74] [cursor=pointer]:
                - /url: "#/pharmacy/adjustments"
                - img [ref=e75]
                - generic [ref=e76]: Kiểm kê điều chỉnh
              - link "Nhập hàng" [ref=e77] [cursor=pointer]:
                - /url: "#/pharmacy/purchase-in"
                - img [ref=e78]
                - generic [ref=e82]: Nhập hàng
              - link "Kiểm kê kho" [ref=e83] [cursor=pointer]:
                - /url: "#/pharmacy/stocktake"
                - img [ref=e84]
                - generic [ref=e89]: Kiểm kê kho
              - link "Xử lý hết hạn" [ref=e90] [cursor=pointer]:
                - /url: "#/pharmacy/expiry"
                - img [ref=e91]
                - generic [ref=e93]: Xử lý hết hạn
          - generic [ref=e94]:
            - button "Thanh toán" [ref=e95] [cursor=pointer]:
              - img [ref=e96]
              - generic [ref=e98]: Thanh toán
              - img [ref=e99]
            - link "Hóa đơn" [ref=e102] [cursor=pointer]:
              - /url: "#/billing/invoices"
              - img [ref=e103]
              - generic [ref=e106]: Hóa đơn
          - generic [ref=e107]:
            - button "Báo cáo" [ref=e108] [cursor=pointer]:
              - img [ref=e109]
              - generic [ref=e111]: Báo cáo
              - img [ref=e112]
            - generic [ref=e114]:
              - link "Tồn kho" [ref=e115] [cursor=pointer]:
                - /url: "#/reports/inventory"
                - img [ref=e116]
                - generic [ref=e120]: Tồn kho
              - link "Lượt khám" [ref=e121] [cursor=pointer]:
                - /url: "#/reports/visit-volume"
                - img [ref=e122]
                - generic [ref=e125]: Lượt khám
              - link "Đơn thuốc" [ref=e126] [cursor=pointer]:
                - /url: "#/reports/prescriptions"
                - img [ref=e127]
                - generic [ref=e130]: Đơn thuốc
          - link "Thông báo" [ref=e131] [cursor=pointer]:
            - /url: "#/notifications"
            - img [ref=e132]
            - generic [ref=e135]: Thông báo
          - generic [ref=e136]:
            - button "Nhân sự" [ref=e137] [cursor=pointer]:
              - img [ref=e138]
              - generic [ref=e143]: Nhân sự
              - img [ref=e144]
            - generic [ref=e146]:
              - link "Lịch ca" [ref=e147] [cursor=pointer]:
                - /url: "#/hr/schedule"
                - img [ref=e148]
                - generic [ref=e150]: Lịch ca
              - link "Chấm công" [ref=e151] [cursor=pointer]:
                - /url: "#/hr/me/timelog"
                - img [ref=e152]
                - generic [ref=e155]: Chấm công
              - link "Nghỉ phép" [ref=e156] [cursor=pointer]:
                - /url: "#/hr/leave/new"
                - img [ref=e157]
                - generic [ref=e160]: Nghỉ phép
          - generic [ref=e161]:
            - button "Quản trị" [ref=e162] [cursor=pointer]:
              - img [ref=e163]
              - generic [ref=e165]: Quản trị
              - img [ref=e166]
            - link "Danh mục thuốc" [ref=e169] [cursor=pointer]:
              - /url: "#/admin/medicines"
              - img [ref=e170]
              - generic [ref=e174]: Danh mục thuốc
          - link "Cài đặt" [ref=e175] [cursor=pointer]:
            - /url: "#/settings"
            - img [ref=e176]
            - generic [ref=e179]: Cài đặt
        - button "Thu nhỏ menu" [ref=e181] [cursor=pointer]:
          - generic [ref=e182]: Thu nhỏ menu
          - img [ref=e183]
      - generic [ref=e185]:
        - banner [ref=e186]:
          - button "Chuyển phòng khám" [ref=e188] [cursor=pointer]:
            - img [ref=e190]
            - generic [ref=e194]: Phong kham MediZen Demo
          - button "Open quick search (Ctrl+K)" [ref=e195] [cursor=pointer]:
            - img [ref=e196]
            - generic [ref=e199]: Tìm kiếm
            - generic [ref=e200]: ⌘K
          - generic [ref=e201]:
            - status "Online" [ref=e202]:
              - generic [ref=e204]: Online
              - 'generic "Sync error: Failed to load Tauri SQL plugin. Ensure app is running in Tauri context." [ref=e3902]': (!)
            - button "Thông báo" [ref=e206] [cursor=pointer]:
              - img [ref=e207]
            - button "VI" [ref=e210] [cursor=pointer]
            - button "Chuyển sang chế độ tối" [ref=e211] [cursor=pointer]:
              - img [ref=e212]
            - button "Chọn giao diện màu" [ref=e214] [cursor=pointer]:
              - img [ref=e215]
            - button "Menu người dùng" [ref=e221] [cursor=pointer]:
              - generic [ref=e222]: DN
              - generic [ref=e223]: Dược sĩ
        - navigation "Breadcrumb" [ref=e2143]:
          - link "Home" [ref=e2144] [cursor=pointer]:
            - /url: "#/dashboard"
            - img [ref=e2145]
          - generic [ref=e2148]:
            - img [ref=e2149]
            - link "Quản trị" [ref=e2151] [cursor=pointer]:
              - /url: "#/admin"
          - generic [ref=e3903]:
            - img [ref=e3904]
            - generic [ref=e3906]: Dịch vụ
        - main [ref=e237]
    - region "Notifications alt+T"
  - generic [ref=e2141]: "0"